---

- name: "Adicionando o repositorio do Ansible"
  apt_repository:
    repo: ppa:ansible/ansible
    update_cache: yes
  tags:
    - repo


- name: "Instalando o pacote 'software-properties-common'"
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
  become: true
  tags:
    - deps


- name: "Instalando o pacote 'Ansible'"
  apt:
    name: ansible
    state: present
    update_cache: yes
  become: true
  tags:
    - ansible