---

- name: "Instalando as dependencias em {{ ansible_os_family }}"
  apt:
    name: "{{ debian_like_deps }}"
    state: present
    update_cache: yes
  tags:
    - deps


- name: "Instalando o pacote 'Ansible' em {{ ansible_os_family }}"
  apt:
    name: ansible
    state: present
    update_cache: yes
  tags:
    - ansible