---

- name: "Instalando as dependencias"
  apt:
    name: "{{ debian_like_deps }}"
    state: present
    update_cache: yes
  tags:
    - deps


- name: "Instalando o pacote 'Ansible' no Debian"
  apt:
    name: ansible
    state: present
    update_cache: yes
  tags:
    - ansible