---

- name: Criando estrutura de diretorios
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0775
    recurse: yes
  with_items:
    - "{{ ansible_user_dir }}/devops/ansible/inventories"
    - "{{ ansible_user_dir }}/devops/ansible/keys"
    - "{{ ansible_user_dir }}/devops/ansible/logs"
    - "{{ ansible_user_dir }}/devops/ansible/playbooks"
    - "{{ ansible_user_dir }}/devops/ansible/roles"
  become: true
  tags:
    - directory


- name: Criando estrutura de diretorios de /etc/ansible
  file:
    path: "/etc/ansible"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
  become: true
  tags:
    - config


- name: Copiando o arquivo de configuracao ansible.cfg
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - config


- name: Atualizando a propriedade roles_path em /etc/ansible/ansible.cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "roles_path"
    line: "roles_path    = {{ ansible_user_dir }}/devops/ansible/roles"
    backrefs: yes
    state: present
  become: true
  tags:
    - config


- name: Atualizando a propriedade log_path em /etc/ansible/ansible.cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "log_path"
    line: "log_path = {{ ansible_user_dir }}/devops/ansible/logs/ansible.log"
    backrefs: yes
    state: present
  become: true
  tags:
    - config


- name: Atualizando a propriedade private_key_file em /etc/ansible/ansible.cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: "#private_key_file"
    line: "#private_key_file = {{ ansible_user_dir }}/ansible/keys/key.pem"
    backrefs: yes
    state: present
  become: true
  tags:
    - config