---
    
- name: "Instalando o Repositorio Epel em {{ ansible_os_family }}"
  yum: 
    name: epel-release
    state: present
  tags:
   - deps
  

- name: "Instalando o pacote 'Ansible' em {{ ansible_os_family }}"
  yum:
    name: ansible
    state: present
  tags:
   - ansible
