---
    
- name: "Instalando o Repositorio Epel"
  yum: 
    name: epel-release
    state: present
  become: true
  tags:
   - deps
  

- name: "Instalando o pacote 'Ansible'"
  yum:
    name: ansible
    state: present
  become: true
  tags:
   - ansible
