---

- name: "Instalando o PIP 3"
  zypper:
   name: python3-pip
   state: present
   force: yes
  become: true
  tags:
   - pip
   - deps


- name: "Atualizando o PIP"
  pip:
    name: pip
    state: latest
  become: true
  tags:
    - pip
    - deps


- name: "Instalando o pacote 'Ansible' pelo PIP"
  pip:
    name: "ansible"
    state: present
  become: true
  tags:
    - pip
    - ansible


- name: Criando estrutura de diretorios de /etc/ansible
  file:
    path: "/etc/ansible"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes
  become: true
  tags:
    - config


- name: Copiando o arquivo de configuracao ansible.cfg
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - config