---

- name: Instalando o build-essential
  apt:
    name: build-essential
    state: present
    update_cache: yes
  become: true
  tags:
    - pip


- name: Instalando o python-setuptools (Python 3)
  apt:
    name: python3-setuptools
    state: present
    update_cache: yes
  become: true
  tags:
    - pip


- name: Instalando o PIP 3
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true
  tags:
    - pip